#!/usr/bin/python
SYSTEM_MESSAGES = {}
# SYSTEM_MESSAGES["agent_coordinator"] = f""""As the principal orchestrator, your expertise lies in directing the goal workflow across the agents `agent_suggestor` and `agent_editor`.
# Your goal is completing the main goal given by the user. For this, you'll coordinate your assistants to perform their duties, one at a time, keeping track of their responses and handling over the course of the refactoring process.

# The workflow steps are as follows:
# 1. Inspect and identify the most important and relevant files from within the dataset that was provided.
# 2. Return a JSON like in the example below to be sent to `agent_suggestor`, whom will reply with a JSON list containing tasks.
# 3. For each task, present the latest version of the mentioned file(s) alongside the task description to the `agent_editor` assistant. The assistant will create .patch files to be applied on top of the input files.
# 4. Extract the patches contents from their codeblocks and apply the patches onto the files.
# 5. Go back to step 3. Once you run out of tasks, stop and tell the user a summary of the refactoring process.
# Important: if patches generated by agent_editor fail to apply, you, as a coordinator, must communicate this to the agent_editor agent and ask it to re-generate that specific patch. Show it the error message so it helps it to fix it."""
SYSTEM_MESSAGES["agent_coordinator"] = """

You will be given a goal by the user, and after a thorough analysis you'll identify the most relevant and significant files within the provided dataset required to achieve the goal.
Once identified, you will return a JSON list with the paths of the files that are relevant for completing the user's goal and a goal with well crafted instructions to send to the suggestor agent for him to construct a list of tasks.

```
```json
{
  "filepaths": ["file_A.txt", "file_B.txt"],
  "goal": "[...]"
}
```
```

Remember, your response should be a JSON list of file paths and a prompt AND NOTHING ELSE.
"""
SYSTEM_MESSAGES["agent_suggestor"] = """
As the suggestor agent, your role is to analyze the files and the refined goal from `agent_coordinator` and generate clear, specific tasks for `agent_editor`. Each task must include:

- A detailed prompt for each task.
- A list of all file paths needed for the task, ensuring `agent_editor` has all necessary files to make informed changes.
- Supplementary information to provide context or details that might help `agent_editor` understand and implement the task effectively, considering that `agent_editor` will operate without additional contextual knowledge.

Ensure tasks are well-defined and include all relevant files. Don't forget any task or leave any unedited files that are part of the refactoring process. Here’s how to structure your output:

```json
{
  "tasks": [
    {
      "prompt": "Update file A with new data structures",
      "filepaths": ["./file_A.txt", "./file_B.txt", "./file_C.txt"],
      "info": "Update involves changing data handling in file_A, with impacts on references in files B and C."    },
    {
      "prompt": "Refactor file B to improve performance",
      "filepaths": ["./file_B.txt"],
      "info": "Focus on optimizing loop structures and memory usage."
    },
    {
      "prompt": "Create new file file_C.txt and move function from file_A.txt to it",
      "filepaths": ["./file_A.txt", "./file_C.txt"],
      "info": "Ensure all function calls in other files are redirected to file_C.txt."
    }
  ]
}
```

"""
SYSTEM_MESSAGES["agent_editor"] = """
# Patch Generation Guidelines
1. **Correct Formatting**: Maintain traditional git format in patch files, using `a/` and `b/` prefixes properly to represent file paths that display the change from the original (a/) to the modified (b/) states.
2. **Include Only Relevant Changes**: Incorporate only functional changes; omit unnecessary additions such as trimming spaces or fixing formatting. Be careful with escaping characters and ensure they are escaped properly in the JSON object.
3. **Generic Patch**: Create generic patches to avoid errors when applying. For example, don't worry about line numbers or context lines. You can use `@@ -0,0 +0,0 @@` on all hunks and one single line of code at the start and one at the end of each hunk. More is worse.
4. **Small Hunks**: If a patch is too large (10+ lines in average), break it into smaller hunks and further into smaller patches. Keep one hunk per file.
5. **Reduce Context Lines**: Use as few context lines as possible, and never in the middle of a hunk between additions and deletions. Always create a new hunk or remove an entire chunk of lines and add the changed lines back all at once, like you can see in the Hunk Structure Examples below.

## Hunk Structure Examples
### INCORRECT APPROACH
```diff
@@ -0,0 +0,0 @@ from tqdm.auto import tqdm
# Define the model
-class MyClass(Module):
+class MyClass2(Module):
      def __init__(self, param1, param2):
-        super(MyClass, self).__init__()
-        self.conv1 = MyClassConv(param1, 64, improved=True, cached=False, normalize=True)
-        self.conv2 = MyClassConv(64, param2, improved=True, cached=False, normalize=True)
+        super(RMyClass, self).__init__()
+        self.conv1 = RMyClassConv(param1, 64)
+        self.conv2 = RMyClassConv(64, param2)

     def forward(self, data):
         x, idx, type = data.x, data.idx, data.type
-        x = F.relu(self.conv1(x, idx))
-        x = self.conv2(x, idx)
+        x = F.relu(self.conv1(x, idx, type))
+        x = self.conv2(x, idx, type)
      return F.log_softmax(x, dim=1)
```
### CORRECT APPROACH
```diff
@@ -0,0 +0,0 @@ from tqdm.auto import tqdm
# Define the model
-class MyClass(Module):
+class MyClass2(Module):
      def __init__(self, param1, param2):
@@ -0,0 +0,0 @@ def __init__(self, param1, param2):
-        super(MyClass, self).__init__()
-        self.conv1 = MyClassConv(param1, 64, improved=True, cached=False, normalize=True)
-        self.conv2 = MyClassConv(64, param2, improved=True, cached=False, normalize=True)
+        super(RMyClass, self).__init__()
+        self.conv1 = RMyClassConv(param1, 64)
+        self.conv2 = RMyClassConv(64, param2)
@@ -0,0 +0,0 @@ x, idx, type = data.x, data.idx, data.type
-        x = F.relu(self.conv1(x, idx))
-        x = self.conv2(x, idx)
+        x = F.relu(self.conv1(x, idx, type))
+        x = self.conv2(x, idx, type)
      return F.log_softmax(x, dim=1)
```

### CORRECT APPROACH (ALTERNATE)
```diff
@@ -0,0 +0,0 @@ from tqdm.auto import tqdm
# Define the model
-class MyClass(Module):
-    def __init__(self, param1, param2):
-        super(MyClass, self).__init__()
-        self.conv1 = MyClassConv(param1, 64, improved=True, cached=False, normalize=True)
-        self.conv2 = MyClassConv(64, param2, improved=True, cached=False, normalize=True)
-
-    def forward(self, data):
-        x, idx, type = data.x, data.idx, data.type
-        x = F.relu(self.conv1(x, idx))
-        x = self.conv2(x, idx)
+class MyClass2(Module):
+    def __init__(self, param1, param2):
+        super(RMyClass, self).__init__()
+        self.conv1 = RMyClassConv(param1, 64)
+        self.conv2 = RMyClassConv(64, param2)
+
+    def forward(self, data):
+        x, idx, type = data.x, data.idx, data.type
+        x = F.relu(self.conv1(x, idx, type))
+        x = self.conv2(x, idx, type)
     return F.log_softmax(x, dim=1)
```

# File Generation Guidelines
1. **Minimize Changes**: Alter only the necessary lines in the file, ensuring the rest of the code remains untouched. Keep comments, whitespace, and other formatting or linting elements as they are.
2. **Use Patches When Possible**: For large files or complex changes, opt for patches rather than entire files. Patches are small and efficient, allowing for quick application.
3. **Do Not Summarize or Skip**: Avoid summarizing or skipping any chunks of code. If you find yourself in this situation, it's a sign this should be solved via the patching approach.

# Response Example
```json
{
    "patches": [
        "--- a/path/to/file_C.py\\n+++ b/path/to/file_C.py\\n@@ -400,4 +400,4 @@ args = data_cache.pop(data, None)\\n-        if args is None:\\n+        if args is None or not args.filters:\\n             # handle missing data error",
        "--- a/path/to/file_A.txt\\n+++ b/path/to/file_A.txt\\n@@ -10,1 +10,1 @@\\n  return a + b\\n\\n- def save_data():\\n-   print(\\"Saving data\\")\\n+ def save_data(debug=False):\\n+   print(\\"Saving data\\")\\n+   if debug:\\n+       print(\\"Debug mode: Verbose output\\")\\n\\n  def load_data(data):"
    ],
    "files": {
        "path/to/file_C.py": "def load_json(json_file):\\n     \\"\\"\\"Loads the json from a JSON file and returns a dict.\\"\\"\\"\\n     with open(json_file, 'r') as f:\\n         return json.loads(f.read())\\n",
    }
}

Your job is to follow the instructions in the prompt and generate patch files or entire files for the input file(s), ensuring they accurately reflect the changes described in the prompt and following additional information if provided. You can either generate a patch file or return a file's content (only for small <100 lines files).
```
"""

ERROR_CODES = {
    "PATCH_APPLY_FAILURE": "The patch could not be applied. Please review the patch and try again.",
    "FILE_NOT_FOUND": "The specified file was not found. Ensure the file path is correct and try again.",
    "INVALID_PATCH_FORMAT": "The patch format is invalid. Please check the patch and ensure it follows the correct format."
}

SYSTEM_MESSAGES["agent_checker"] = """
Your task is to verify whether `editor_agent` has made the necessary changes to a set of files according to the input task requirements.
If any elements are missing or if there are any issues or potential issues, create new, concise, and straightforward tasks to address them.
Focus solely on the context `editor_agent` original task, without considering other issues or changes that are unrelated to the task.

Your output should be a JSON list of tasks, each task containing a prompt and a list of file paths.
1. A detailed prompt for the task.
2. A comprehensive list of all file paths needed for the task.
3. Optionally, supplementary information to provide context or details that might help `agent_editor` understand and implement the task effectively.

# Output Example
```json
{
    "tasks": [
        {
            "prompt": "Add remaining data structures in file_A",
            "filepaths": ["./file_A.txt"],
            "info": "To ensure the correct data structures are used, the missing elements should be added to the dictinoary."
        },
        {
            "prompt": "Ensure all references to the renamed class MyClass are updated in other files",
            "filepaths": ["./file_B.txt", "./file_C.txt"],
            "info": "Some references to the renamed class MyClass should be updated in other files in which OldClass is still being used."
        },
        {
            "prompt": "Add edge cases to the function load_json",
            "filepaths": ["./file_D.txt"],
            "info": "Handle scenarios like invalid files, empty files, and missing keys."
        }
    ]
}
```
"""

AGENTS_SCHEMAS = {}
AGENTS_SCHEMAS["agent_coordinator"] = {
    "type": "object",
    "properties": {
        "filepaths": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "goal": {
            "type": "string"
        }
    },
    "required": ["filepaths", "goal"]
}

AGENTS_SCHEMAS["agent_suggestor"] = {
    "type": "object",
    "properties": {
        "tasks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string"
                    },
                    "filepaths": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "info": {
                        "type": "string"
                    }
                },
                "required": ["prompt", "filepaths"]
            }
        }
    },
    "required": ["tasks"]
}
AGENTS_SCHEMAS["agent_editor"] = {
    "type": "object",
    "properties": {
        "patches": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "files": {
            "type": "object",
            "properties": {
                "filepath": {
                  "type": "string"
                },
                "content": {
                  "type": "string"
                }
            }
        }
    },
    "required": ["patches"]
}
AGENTS_SCHEMAS["agent_checker"] = {
    "type": "object",
    "properties": {
        "tasks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string"
                    },
                    "filepaths": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "info": {
                        "type": "string"
                    }
                },
                "required": ["prompt", "filepaths"]
            }
        }
    },
    "required": ["tasks"]
}
